spring:
    application:
        name: catalog-service
    config:
        import: "optional:configserver:"
    cloud:
        config:
            uri: http://localhost:8888
            request-connect-timeout: 5000
            request-read-timeout: 5000
            fail-fast: false # In production, set to true
            retry:
                max-attempts: 6
                initial-interval: 1000
                max-interval: 2000
                multiplier: 1.1
    datasource:
        username: user
        password: s3cr3t
        url: jdbc:postgresql://localhost:5432/gyenyamedb_catalog
        hikari:
            connection-timeout: 2000
            maximum-pool: 5
server:
    port: 8080
    tomcat:
        connection-timeout: 2s
        keep-alive-timeout: 15s
        threads:
            max: 50
            min-spare: 5
application:
    greeting: Welcome to the Gye Nyame Book catalog!
management:
    endpoints:
        web:
            exposure:
                include: refresh
